apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: postgresql-ha
  labels: 
    app: postgresql
spec:
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
    protocol: TCP
  clusterIP: None
  selector:
    app: postgresql

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-read
  namespace: postgresql-ha
  labels: 
    app: postgresql
spec:
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-metrics
  namespace: postgresql-ha
  labels: 
    app: postgresql-metrics
    jobLabel: postgresql
    release: prometheus-operator
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9187
    targetPort: 9187
    protocol: TCP
  selector:
    app: postgresql
